General code clean-up in transform.py.
nasa/harmony-gdal-adapter pull request #23
Opened 2022-11-26 06:11 UTC by owenlittlejohns

## Description

This PR primarily covers some linting cleanup in `gdal_subsetter/transform.py`. It's not everything, and not meant to be exhaustive, but I had some time today, and wanted to make a start.

The main things covered in this PR:

* Updates to the `checkstackable` class method (now `is_stackable`), including addition of unit tests for it.
* Augmentation of regular expression to find matching `SUBDATASET` output from `gdalinfo` (I'll pop a comment on that to explain it).
* Adoption of `os.path.join()` when concatenating file paths.
* Standardising the use of either double or single quotation marks. PEP8 encourages the use of one or the other, not both. This code had a lot of both. I went with my personal preference of single quotes.
* Adopting f-strings instead of older style "%s" or `str.format()` syntaxes.
* Ensuring the correct amount of whitespace around operators, commas, etc.
* Changing a couple of variable names here and there.
* Some other minor tweaks here and there, probably more than I should have done in one PR.

## Jira Issue ID

Long-IP, currently doesn't have a ticket.

## Local Test Steps

* Pull this branch locally.
* Build HGA with `bin/build-image`.
* Pull the accompanying PR for the HGA regression tests.
* Run those. They should all pass.

## PR Acceptance Checklist
* ~~Jira ticket acceptance criteria met.~~
* [x] `version.txt` and `CHANGE.md` updated if any service code is changed.
* [x] Tests added/updated and passing.
* ~~Documentation updated (if needed).~~

2022-11-26 06:35 UTC, owenlittlejohns commented on gdal_subsetter/transform.py
> +    def is_stackable(self, files_to_stack: str) -> bool:
This is one of the two main places where I've tweaked things more significantly. The behaviour should be the same as the older version, though (and now we have accompanying unit tests to ensure that functionality persists through future iterations).

Part of me was tempted to extract this into a new module, where it doesn't actually make use of any of the other class attributes or methods, but I thought I'd start with just a quick refactor in place for now.

2022-11-26 06:35 UTC, owenlittlejohns commented on gdal_subsetter/transform.py
> +        same_projection = len(projections) == 1
I could have jammed these conditions directly into the long boolean condition in the return statement, but I reckon this is probably more legible, even though it adds a few lines of code.

2022-11-26 06:35 UTC, owenlittlejohns commented on gdal_subsetter/transform.py
> +        # RasterFormat = 'GTiff'
For reference, `pylint` dislikes inline comments that don't have a space after the `#`.

2022-11-26 06:35 UTC, owenlittlejohns commented on gdal_subsetter/transform.py
> +                           is not None), None)
This is the second of the two more significant changes I made this time around. I noticed that the old version of the HGA regression Sentinel test-case 13 was failing for a silly reason. There is a variable (that probably shouldn't be processed anyway) in the root group called `productBoundingBox`. In the `gdalinfo` output the first line that referred to that variable was part of the metadata:

```
NC_GLOBAL#ogr_layer_name=productBoundingBox
```

However, the thing that should have matched was the subsequent line:

```
SUBDATASET_1_NAME=NETCDF:"/Users/olittlej/Downloads/S1-GUNW-A-R-166-tops-20200313_20200206-014119-34455N_32574N-PP-1749-v2_0_2.nc":productBoundingBox
```

This change guards against that. (It also drops the lambda function in favour of a generator, which I think(?) is considered more "Pythonic")

2022-11-26 06:35 UTC, owenlittlejohns commented on gdal_subsetter/transform.py
> +        dst.history = f'{datetime.utcnow():%d/%m/%Y %H:%M:%S} (UTC)'
I thought this was a pretty cool trick - I didn't previously know that f-strings were smart enough to format datetimes, but I suppose they should handle them as datetimes are part of the Python standard library.

2022-11-28 21:04 UTC, flamingbear requested changes
Looks good, had a couple of cleanup items to fix though.

2022-11-29 01:51 UTC, owenlittlejohns commented on gdal_subsetter/transform.py
>                  if "degree" in unit.lower():
- [ ] Thanks for catching some stagglers. Will update!

2022-11-29 01:53 UTC, owenlittlejohns commented on gdal_subsetter/transform.py
> +                           if re.search(f'SUBDATASET.*:*{layer_id}$', line)
- [ ] Yeah - I think I prefer to remove that colon all together. I agree that colons can be a bit sneaky in regular expressions. (I _think_ it's performing a match, here, but let's remove any uncertainty.

2022-11-29 01:55 UTC, owenlittlejohns commented on gdal_subsetter/transform.py
> +    def is_stackable(self, files_to_stack: str) -> bool:
- [ ] Good catch - I think we both had half the answer: `List[str]` would probably be the best thing.

Generally - I was a bit half-hearted in adding the types. But I added the ones that were obvious. I think when we understand the code well enough to have all function/method signatures with types, that'll help reading the code further down the road. (Of course, getting that better understanding is 90% of the battle)

2022-11-29 01:55 UTC, owenlittlejohns commented on gdal_subsetter/transform.py
> +                                      attribute_value.rstrip("\n"))
- [ ] Update another missed double quotes string.

2022-11-29 02:53 UTC, flamingbear commented on gdal_subsetter/transform.py
> +                           if re.search(f'SUBDATASET.*:*{layer_id}$', line)
I'm pretty sure it's not matching in the example you provided.  the `.*` grabs everything up to layer_id.  `:*` is 0 or more `:`s. and it just gets zero.  ( I was confused so I played in the repl).

2022-11-29 03:00 UTC, flamingbear approved these changes
Looks good. Thanks.

2022-11-29 05:11 UTC, owenlittlejohns commented on gdal_subsetter/transform.py
> +                           if re.search(f'SUBDATASET.*:*{layer_id}$', line)
Fair enough. Probably good to get rid of it, then. Thanks for catching that.

2022-11-29 07:57 UTC, merged